# Generated by Django 3.1.7 on 2021-04-19 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='state',
            new_name='internetState',
        ),
    ]
