# Generated by Django 3.1.7 on 2021-04-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20210419_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
