# Generated by Django 2.2.5 on 2021-04-20 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='internetState',
        ),
    ]
