# Generated by Django 2.2.5 on 2021-04-22 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_client_internetstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lastCommunication',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 23, 8, 11, 754541)),
        ),
    ]
