# Generated by Django 2.2.5 on 2021-04-22 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20210422_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lastCommunication',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
